border_width = 2
margin = [4, 4]
default_border_color = "#12121b"
floating_border_color = "#4F95C8"
focused_border_color = "#d8cdd0"


col1 = "#22569E"
col2 = "#40499B"
col3 = "#5D5C99"
col4 = "#996194"
col5 = "#D96195"
col6 = "#4F95C8"
col7 = "#d8cdd0"
col8 = "#978f91"
col9 = "#22569E"
col10 = "#40499B"
col11 = "#5D5C99"
col12 = "#996194"
col13 = "#D96195"
col14 = "#4F95C8"
col15 = "#d8cdd0"



background = "#12121b"
foreground = "#d8cdd0"
