#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
#this is your scriptpath
# echo $SCRIPTPATH

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

########## This script makes the colors of your polybar and terminals#########
sh $SCRIPTPATH/scripts/wal.sh
##############################################################################

#change your keyboard if you need it - azerty or qwerty
#setxkbmap -layout be
keybLayout=$(setxkbmap -v | awk -F "+" '/symbols/ {print $2}')

if [ $keybLayout = "be" ]; then
  cp ~/.config/leftwm/config-azerty.ron ~/.config/leftwm/config.ron
fi

leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# keybindings daemon
# put your personal keybinds inside your theme and use those
if [ -f "$SCRIPTPATH/sxhkd/sxhkdrc" ] ; then
  # check if there is a keybinds-folder inside your personal theme and use it
  # to use the standard keybinds, delete the dir sxhkd inside your theme
  sxhkd -c ~/.config/leftwm/themes/current/sxhkd/sxhkdrc &
else
  # standard keybinds
  sxhkd -c ~/.config/leftwm/sxhkd/sxhkdrc &
fi

function run {
  if ! pgrep -x $(basename $1 | head -c 15) 1>/dev/null;
  then
    $@&
  fi
}

# diversity of apps to start
nm-applet &
pamac-tray &
xfce4-power-manager &
numlockx on &
blueberry-tray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
volumeicon &
run xfce4-clipman
#conky -c ~/.config/leftwm/system-overview &
#nitrogen --restore &
#caffeine &
#vivaldi-stable &
#firefox &
#thunar &
#dropbox &
#insync start &
#discord &
#spotify &
#atom &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config "$SCRIPTPATH"/picom.conf &> /dev/null &
  #picom --config $HOME/.config/leftwm/themes/current/picom.conf --experimental-backends &> /dev/null &
  #picom &> /dev/null &
  #picom --experimental-backends &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton --config $HOME/.config/leftwm/themes/current/compton.conf &> /dev/null &
fi

# Set background
#if [ -x "$(command -v feh)" ]; then
#    feh --bg-fill --no-fehbg $SCRIPTPATH/background.jpg
#fi

# EWW
eww daemon
eww open bar -c $SCRIPTPATH/eww
eww update user=$(whoami) -c $SCRIPTPATH/eww
